export const courses = [
  {
    id: 1,
    title: "Curso de Pthon Para Ciencia De Datos",
    description:
      "Domina Python para análisis y visualización de datos con NumPy, Pandas y Matplotlib. Desarrolla habilidades para proyectos reales de Data  Science.",
    price: 100,
    category: "Programming",
    status: "published",
    created_at: "2021-10-10",
    instructor: {
      username: "john_doe",
      first_name: "John",
      last_name: "Doe",
      email: "",
    },
    estimate: "4 hours",
    level: "basic",
    rating: 2,
  },
  {
    id: 2,
    title: "JavaScript",
    description:
      "Aprende expresiones habituales en inglés y practica frases simples para  presentarte y responder What's your name? al decir tu nombre y How  old are you? para indicar tu edad.  Usar el alfabeto en inglés para  deletrear palabras, identifica números básicos y adquiere vocabulario  sobre los días de la semana y objetos cotidianos. Domina el verbo to  be en expresiones cortas para hablar de tu profesión y responde  preguntas con who para hablar de alguien más.",
    price: 100,
    category: "Programming",
    status: "published",
    created_at: "2021-10-10",
    instructor: {
      username: "john_doe",
      first_name: "John",
      last_name: "Doe",
      email: "",
    },
    estimate: "4 hours",
    level: "basic",
    rating: 3.2,
  },
  {
    id: 3,
    title: "React",
    description: "Learn React from scratch",
    price: 100,
    category: "Programming",
    status: "published",
    created_at: "2021-10-10",
    instructor: {
      username: "john_doe",
      first_name: "John",
      last_name: "Doe",
      email: "",
    },
    estimate: "4 hours",
    level: "basic",
    rating: 5,
  },
  {
    id: 4,
    title: "Django",
    description: "Learn Django from scratch",
    price: 100,
    category: "Programming",
    status: "published",
    created_at: "2021-10-10",
    instructor: {
      username: "john_doe",
      first_name: "John",
      last_name: "Doe",
      email: "",
    },
    estimate: "4 hours",
    level: "basic",
    rating: 5,
  },
];
